[package]
name = "fast_fibonacci"
version = "0.1.0"
authors = ["3585"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.14"